//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class GlobalVariables:MonoBehaviour
{
	public static GlobalVariables instance;

	public static GlobalVariables Instance {
		get {
			if (instance == null) {
				instance = new GlobalVariables ();
			}
			return instance;
		}
	}

	public static int nFruitFails = 0;
	public static bool isPause = false;

	public static string FoamPath = "Prefabs/Foam";
	public static string StainPath = "Prefabs/Stain";
	public static string DirectedStainPath = "Prefabs/DirectedStain";
	public static string CriticalPath = "Prefabs/Critical";
	public static string ComboPath = "Prefabs/Combo";
	public static string FreezePath = "Prefabs/Freeze";
	public static string StarPath = "Prefabs/Star";
    public static float BackZ = 5;
    public static float FrontZ = -5;

	public static bool IsPause = false;
	public static int Score = 0;




}
